name: GradPrint
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.8.18
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.1.0
    - adversarial-robustness-toolbox==1.17.1
    - advertorch==0.2.3
    - alembic==1.13.1
    - androguard==3.3.5
    - apkinspector==1.2.3
    - asn1crypto==1.5.1
    - asttokens==2.4.1
    - astunparse==1.6.3
    - attrs==24.3.0
    - backcall==0.2.0
    - banal==1.0.6
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - cachetools==4.2.4
    - click==8.1.7
    - colorama==0.4.6
    - contourpy==1.1.1
    - cycler==0.12.1
    - dataset==1.6.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docopt==0.6.2
    - eagerpy==0.29.0
    - executing==2.0.1
    - fastjsonschema==2.21.1
    - fonttools==4.49.0
    - foolbox==3.1.1
    - frida==16.2.1
    - future==1.0.0
    - gast==0.3.3
    - gitdb==4.0.11
    - gitpython==3.1.42
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - greenlet==3.0.3
    - grpcio==1.62.1
    - h5py==2.10.0
    - importlib-metadata==7.0.2
    - importlib-resources==6.1.3
    - ipython==8.12.3
    - jedi==0.19.1
    - jinja2==3.1.5
    - joblib==1.3.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyterlab-pygments==0.3.0
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.5
    - loguru==0.7.2
    - lxml==5.2.1
    - mako==1.3.3
    - markdown==3.5.2
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.7
    - mistune==3.1.0
    - mutf8==1.0.6
    - nbclient==0.10.1
    - nbconvert==7.16.5
    - nbformat==5.10.4
    - networkx==3.1
    - numpy==1.22.4
    - oauthlib==3.2.2
    - opencv-python==4.10.0.82
    - opt-einsum==3.3.0
    - packaging==24.0
    - pandas==2.0.3
    - pandocfilters==1.5.1
    - parso==0.8.4
    - patsy==0.5.6
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pipreqs==0.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - prompt-toolkit==3.0.43
    - protobuf==3.20.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pydot==2.0.0
    - pygments==2.18.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==26.2.0
    - referencing==0.35.1
    - requests-oauthlib==1.4.0
    - rpds-py==0.20.1
    - rsa==4.9
    - scikit-learn==1.0.2
    - scipy==1.4.1
    - seaborn==0.13.2
    - six==1.16.0
    - smmap==5.0.1
    - soupsieve==2.6
    - sqlalchemy==1.4.52
    - stack-data==0.6.3
    - statsmodels==0.14.1
    - tensorboard==2.2.2
    - tensorboard-data-server==0.7.2
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==2.4.0
    - threadpoolctl==3.3.0
    - tinycss2==1.2.1
    - tinydb==4.8.0
    - torchlars==0.1.2
    - tornado==6.4.2
    - tqdm==4.66.2
    - traitlets==5.14.3
    - tzdata==2024.1
    - wcwidth==0.2.13
    - webencodings==0.5.1
    - werkzeug==3.0.1
    - wrapt==1.16.0
    - yarg==0.1.9
    - zipp==3.17.0
prefix: /root/miniconda3/envs/detectors_view
